// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Recrovit.RecroGridFramework.Identity;

namespace Recrovit.RecroGridFramework.Identity.Migrations.Oracle
{
    [DbContext(typeof(IdentityDbContextBaseMigrOracle))]
    [Migration("20201124000001_rgf_identity_v1_0")]
    partial class rgf_identity_v1_0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Recrovit.RecroGridFramework.Identity.Models.RGFRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnName("ROLEID")
                        .HasColumnType("NVARCHAR2(255)")
                        .HasMaxLength(255);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnName("ROLENAME")
                        .HasColumnType("NVARCHAR2(255)")
                        .HasMaxLength(255);

                    b.Property<string>("RoleScope")
                        .HasColumnName("ROLESCOPE")
                        .HasColumnType("NVARCHAR2(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Source")
                        .HasColumnName("SOURCE")
                        .HasColumnType("NVARCHAR2(16)")
                        .HasMaxLength(16);

                    b.HasKey("RoleId")
                        .HasName("PK_RGF_IDENTITYROLE");

                    b.ToTable("RGF_IDENTITYROLE");

                    b.HasData(
                        new
                        {
                            RoleId = "1",
                            RoleName = "Administrators",
                            Source = "RGF"
                        },
                        new
                        {
                            RoleId = "2",
                            RoleName = "Users",
                            Source = "RGF"
                        });
                });

            modelBuilder.Entity("Recrovit.RecroGridFramework.Identity.Models.RGFUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("USERID")
                        .HasColumnType("NVARCHAR2(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Language")
                        .HasColumnName("LANGUAGE")
                        .HasColumnType("NVARCHAR2(3)")
                        .HasMaxLength(3);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("USERNAME")
                        .HasColumnType("NVARCHAR2(255)")
                        .HasMaxLength(255);

                    b.HasKey("UserId")
                        .HasName("PK_RGF_IDENTITYUSER");

                    b.ToTable("RGF_IDENTITYUSER");
                });

            modelBuilder.Entity("Recrovit.RecroGridFramework.Identity.Models.RGFUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("USERID")
                        .HasColumnType("NVARCHAR2(255)")
                        .HasMaxLength(255);

                    b.Property<string>("RoleId")
                        .HasColumnName("ROLEID")
                        .HasColumnType("NVARCHAR2(255)")
                        .HasMaxLength(255);

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_RGF_IDENTITYUSERROLE");

                    b.HasIndex("RoleId")
                        .HasName("IX_RGF_IDENTITYUSERROLE_ROLEID");

                    b.ToTable("RGF_IDENTITYUSERROLE");
                });

            modelBuilder.Entity("Recrovit.RecroGridFramework.Identity.Models.RGFUserRole", b =>
                {
                    b.HasOne("Recrovit.RecroGridFramework.Identity.Models.RGFRole", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RGF_IDENTITYUSERROLE_RGF__1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recrovit.RecroGridFramework.Identity.Models.RGFUser", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_RGF_IDENTITYUSERROLE_RGF__2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
