// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recrovit.RecroGridFramework.Identity;

namespace Recrovit.RecroGridFramework.Identity.Migrations.SQLServer
{
    [DbContext(typeof(IdentityDbContextBaseMigrSQLServer))]
    partial class IdentityDbContextBaseMigrSQLServerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Recrovit.RecroGridFramework.Identity.Models.RGFRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnName("RoleId")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnName("RoleName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("RoleScope")
                        .HasColumnName("RoleScope")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Source")
                        .HasColumnName("Source")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.HasKey("RoleId")
                        .HasName("PK_RGF_IdentityRole");

                    b.ToTable("RGF_IdentityRole");

                    b.HasData(
                        new
                        {
                            RoleId = "1",
                            RoleName = "Administrators",
                            Source = "RGF"
                        },
                        new
                        {
                            RoleId = "2",
                            RoleName = "Users",
                            Source = "RGF"
                        });
                });

            modelBuilder.Entity("Recrovit.RecroGridFramework.Identity.Models.RGFUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Language")
                        .HasColumnName("Language")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("UserName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("UserId")
                        .HasName("PK_RGF_IdentityUser");

                    b.ToTable("RGF_IdentityUser");
                });

            modelBuilder.Entity("Recrovit.RecroGridFramework.Identity.Models.RGFUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("RoleId")
                        .HasColumnName("RoleId")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_RGF_IdentityUserRole");

                    b.HasIndex("RoleId")
                        .HasName("IX_RGF_IdentityUserRole_RoleId");

                    b.ToTable("RGF_IdentityUserRole");
                });

            modelBuilder.Entity("Recrovit.RecroGridFramework.Identity.Models.RGFUserRole", b =>
                {
                    b.HasOne("Recrovit.RecroGridFramework.Identity.Models.RGFRole", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_RGF_IdentityUserRole_RGF_IdentityRole_RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recrovit.RecroGridFramework.Identity.Models.RGFUser", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_RGF_IdentityUserRole_RGF_IdentityUser_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
